### ISSUE TITLE
Actor Id Not Picked On the Initiated call

### ISSUE THREAD

**Issue by sherrif10** [johnsonandjohnson/openmrs-module-callflows#3]
Hello @pwargulak @druchniewicz  , we are having a serious issue with all our instances at IDI. When we initiate a call , actor id is not picked , on the other side, when you schedule a call, actor id is picked. what would be the quick solution.Thank you

**Comment by druchniewicz** [comment]
> Hello @pwargulak @druchniewicz , we are having a serious issue with all our instances at IDI. When we initiate a call , actor id is not picked , on the other side, when you schedule a call, actor id is picked. what would be the quick solution.Thank you

Find the appropriate endpoint in CallController that is triggered when init call is performed. This is probably this endpoint: _/person/{personUuid}/out/{configName}/flows/{name}.{extension}_ (method name: handleOutgoingByPersonUuid(...)
There are 'additionalParams' passed to 'makeCall' method. So far only 'phone' and 'personId' params are passed so you probably just have to add extra param with 'actorId' key something like that: _additionalParams.put(Constants.PARAM_ACTOR_ID, person.getPersonId());_

Please try this potential solution

**Comment by sherrif10** [comment]
Thanks for Quick response, it seems even we need to add actorId params under this url 
        ("/callflows/person/%s/out/voxeo/flows/MainFlow.vxml?&customParam=%s",   is that true. Kindly guide me.

**Comment by druchniewicz** [comment]
if you add actorId param in CallController (as I described in my answer above) then probably you don't have to add anything else anywhere

**Comment by sherrif10** [comment]
Thanks, there is  a failure on this line https://github.com/johnsonandjohnson/openmrs-module-callflows/blob/main/omod/src/main/java/org/openmrs/module/callflows/web/controller/CallController.java#L589
